from django.db import models
from google import genai
from core.settings import GEMINI_API_KEY, IMAGE_GENERATION_SYS_PROMPT
import logging
import tempfile
from typing import Optional, Dict
from .utils import upload_ai_image

logger = logging.getLogger(__name__)


class ImageGenerationModel:
    """
    Model for generating images using Google's Imagen API and uploading them to S3
    """

    def __init__(self):
        self.client = genai.Client(api_key=GEMINI_API_KEY)

    def create_image(
        self,
        madlib_text: str,
        madlib_id: str,
        extra_prompt_args: Optional[Dict] = None
    ) -> Optional[str]:
        """
        Generate an image using Gemini's Imagen API and upload to S3

        Args:
            madlib_text: string of user filled madlib text
            madlib_id: ID of the associated madlib (used for S3 path organization)
            extra_prompt_args: Optional dict containing style parameters like:
                - 'style': Image style (e.g., 'photorealistic', 'anime', 'watercolor')
                - 'aspect_ratio': Image aspect ratio ('1:1', '3:4', '4:3', '9:16', '16:9')
            
        Example extra_prompt_args:
            {
                'style': 'watercolor painting',
                'aspect_ratio': '16:9',
            }

        Returns:
            String URL of the uploaded image on S3, or None if generation/upload failed
        """
        try:
            # Build the full prompt
            full_prompt = self._build_full_prompt(madlib_text, extra_prompt_args)
            logger.debug(f"Generating image with prompt: '{full_prompt[:100]}...'")

            # Configure generation parameters
            config = self._build_generation_config(extra_prompt_args)

            # Generate image using Imagen API
            response = self.client.models.generate_images(
                model='imagen-4.0-fast-generate-001',
                prompt=full_prompt,
                config=config  # type: ignore[arg-type]
            )

            if not response.generated_images:
                logger.error("No images were generated by the API")
                return None

            # Get the first generated image
            generated_image = response.generated_images[0]
            if generated_image:
                logger.info(f"Successfully generated image")
            else:
                logger.error("Failed to generate image")
                
            # Save to temporary file
            temp_file_path = self._save_to_temp_file(generated_image)

            # Upload to S3
            image_url = upload_ai_image(temp_file_path, madlib_id)

            if image_url:
                logger.info(f"Successfully uploaded image to: {image_url}")
            else:
                logger.error("Failed to upload image to S3")

            
            return image_url

        except Exception as e:
            logger.error(f"Error generating image: {e}")
            return None

    def _build_full_prompt(
        self,
        madlib_text: str,
        extra_prompt_args: Optional[Dict] = None
    ) -> str:
        """
        Build the full prompt by combining system prompt, main prompt, and style args

        Args:
            madlib_text: User filled in madlib
            system_prompt: Optional system-level instructions
            extra_prompt_args: Optional dict with style parameters

        Returns:
            Combined prompt string
        """
        prompt_parts = []

        # Add system prompt if provided
        if IMAGE_GENERATION_SYS_PROMPT:
            prompt_parts.append(IMAGE_GENERATION_SYS_PROMPT)

        # Add madlib text
        prompt_parts.append(madlib_text)

        # Add style information if provided
        if extra_prompt_args and 'style' in extra_prompt_args:
            style = extra_prompt_args['style']
            prompt_parts.append(f"Style: {style}")

        return ". ".join(prompt_parts)

    def _build_generation_config(self, extra_prompt_args: Optional[Dict] = None) -> Dict:
        """
        Build the generation config dictionary from extra_prompt_args

        Args:
            extra_prompt_args: Optional dict with configuration parameters

        Returns:
            Configuration dictionary (SDK accepts both dict and GenerateImagesConfig)
        """
        # default configuration values
        config_params = {
            'number_of_images': 1,
            'aspect_ratio': '1:1'
        }

        # Override defaults with provided extra_prompt_args
        if extra_prompt_args:
            if 'aspect_ratio' in extra_prompt_args:
                config_params['aspect_ratio'] = extra_prompt_args['aspect_ratio']

            if 'person_generation' in extra_prompt_args:
                config_params['person_generation'] = extra_prompt_args['person_generation']

        return config_params

    def _save_to_temp_file(self, generated_image) -> str:
        """
        Save generated image to a temporary file

        Args:
            generated_image: Generated image object from Imagen API

        Returns:
            Path to the temporary file
        """
        # Create a temporary file
        temp_file = tempfile.NamedTemporaryFile(delete=False, suffix='.png')
        temp_file_path = temp_file.name

        # Save the image
        generated_image.image.save(temp_file_path)
        temp_file.close()

        logger.debug(f"Image saved to temporary file: {temp_file_path}")
        return temp_file_path
